/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package imagecomparison;

import nu.pattern.OpenCV;
import java.nio.file.Path;
import java.nio.file.Paths;

public class App {
    static {
        OpenCV.loadLocally();
    }

    public static void main(String[] args) {

        System.out.println("Working directory is" + System.getProperty("user.dir"));
        Path path1 = Paths.get(System.getProperty("user.dir"), "src", "main", "resources", "images", "feature.jpg");
        Path path2 = Paths.get(System.getProperty("user.dir"), "src", "main", "resources", "images", "Image2.jpg");
        FeatureMatching featureMatching = new FeatureMatching();
        featureMatching.match(path1.toString(), path2.toString());
    }

    public String getGreeting() {
        return "Hello World";
    }
}
